### PR TITLE
Fix configuration file error

### PR DESCRIPTION
**Pull request by 3cxc**
### **_English:_** 
Fix the issue that causes an error when the main interface music configuration file is empty. (**_@Bustling114_** )(876e53e98c0206ae8e3dcfafe5a2e3871828ea01)
#
### **_中文:_**
修复部分情况下主界面音乐配置文件为空会引发报错的问题(**_@Bustling114_** )(876e53e98c0206ae8e3dcfafe5a2e3871828ea01)

### CODE REVIEW

**Review by GAmiezui — APPROVED** [review]
cnm

**Review by GAmiezui — APPROVED** [review]
ok

**Comment by Bustling114** [comment]
qnmd












Bustling
***@***.***






---Original---
From: ***@***.***&gt;
Date: Sun, Nov 26, 2023 22:55 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Nebula-Studios/DimenBeat] Fix configuration file error (PR #17)




 
@GAmiezui approved this pull request.
 
cnm

**Comment by 3cxc** [comment]
The merge request is invalid as it has already been completed in #18

**Pull request closed without merging**
